[project]
name = "pharmacology-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dspy>=3.0.3",
    "gradio>=5.49.1",
    "plotly>=6.3.1",
]
